service: course-finder-backend
frameworkVersion: '2'
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  login:
    handler: src/api/auth/auth.login
    events:
      - http:
          path: /api/login
          method: post
          cors:
            origin: "*"
            headers:
              - "*"

  fetchYoutubeResults:
    handler: src/api/results/youtubeResults.getResults
    events:
      - http:
          path: /api/youtubeResults
          method: get
          cors:
            origin: "*"
            headers:
              - "*"
              
  fetchCourseraResults:
    handler: src/api/results/courseResults.getResults
    events:
      - http:
          path: /api/courseResults
          method: get
          cors:
            origin: "*"
            headers:
              - "*"
          
  fetchBlogResults:
    handler: src/api/results/googleResults.getResults
    events:
      - http:
          path: /api/blogResults
          method: get
          cors:
            origin: "*"
            headers:
              - "*"
          